"""job records its operator

Revision ID: 2ec3399d0a5b
Revises: fdfc0bc1b36a
Create Date: 2026-09-05 15:06:08.566301
"""
import sqlalchemy as sa

from alembic import op


revision = '2ec3399d0a5b'
down_revision = 'fdfc0bc1b36a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('profile_id', sa.String(length=32), nullable=False,
                            server_default=''))
    op.create_index(op.f('ix_jobs_profile_id'), 'jobs', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_profile_id'), table_name='jobs')
    op.drop_column('jobs', 'profile_id')
    # ### end Alembic commands ###
