"""operator profiles, variants, preferences

Revision ID: 8d38fc4b91b8
Revises: b8c4beefac25
Create Date: 2026-09-05 03:06:38.393776
"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

revision = '8d38fc4b91b8'
down_revision = 'b8c4beefac25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('style_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_profiles_name'), 'operator_profiles', ['name'], unique=True)
    op.create_table('preferences',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('output_type', sa.String(length=64), nullable=False),
    sa.Column('chosen_approach', sa.String(length=120), nullable=False),
    sa.Column('rejected_approaches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['operator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferences_job_id'), 'preferences', ['job_id'], unique=False)
    op.create_index(op.f('ix_preferences_profile_id'), 'preferences', ['profile_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('artefact_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=8), nullable=False),
    sa.Column('approach', sa.String(length=120), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('qa', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('export_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chosen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artefact_id', 'label', name='uq_variant_artefact_label')
    )
    op.create_index(op.f('ix_variants_artefact_id'), 'variants', ['artefact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variants_artefact_id'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_preferences_profile_id'), table_name='preferences')
    op.drop_index(op.f('ix_preferences_job_id'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_operator_profiles_name'), table_name='operator_profiles')
    op.drop_table('operator_profiles')
    # ### end Alembic commands ###
