"""artefact feedback

Revision ID: fdfc0bc1b36a
Revises: 8d38fc4b91b8
Create Date: 2026-09-05 14:07:51.808858
"""
import sqlalchemy as sa

from alembic import op


revision = 'fdfc0bc1b36a'
down_revision = '8d38fc4b91b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('artefact_id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('output_type', sa.String(length=64), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artefact_id', 'profile_id', name='uq_feedback_artefact_profile')
    )
    op.create_index(op.f('ix_feedback_artefact_id'), 'feedback', ['artefact_id'], unique=False)
    op.create_index(op.f('ix_feedback_profile_id'), 'feedback', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_profile_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_artefact_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
